---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: dns
  namespace: platform
spec:
  type: 0
  resourceID: {{ .azure_dns_msi_id }}
  clientID: {{ .azure_dns_msi_client_id }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: dns
  namespace: platform
spec:
  azureIdentity: dns
  selector: dns
