---
image:
  repository: opsteadyos.azurecr.io/external-dns/external-dns
  tag: v0.10.2

provider: azure

imagePullSecrets:
  - name: management-acr

priorityClassName: "system-cluster-critical"

nodeSelector:
  name: system

logLevel: debug
logFormat: json
policy: sync
registry: txt

extraArgs:
  - --azure-resource-group={{ .local_foundation_resource_group }}

domainFilters:
  - {{ .local_foundation_public_zone_name }}

extraVolumes:
  - name: azure-dns-config
    secret:
      secretName: azure-dns-config

extraVolumeMounts:
  - name: azure-dns-config
    mountPath: /etc/kubernetes/
    readOnly: true
