apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: { { .azure_certificates_letsencrypt_email } }
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt
    solvers:
      - dns01:
        azureDNS:
          subscriptionID: { { .azure_foundation_subscription_id } }
          resourceGroupName: { { .azure_foundation_resource_group } }
          hostedZoneName: { { .azure_foundation_public_zone_name } }
          environment: AzurePublicCloud
