source:
  repo:
    kind: HELM
    url: https://charts.dexidp.io
target:
  containerRegistry: opsteadyos.azurecr.io
  containerRepository: opsteadyos.azurecr.io
  repo:
    kind: OCI
    url: https://opsteadyos.azurecr.io/helm
charts:
  - dex
