image:
  repository: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon/aws-load-balancer-controller
  # TODO: update to Opsteady ACR (https://github.com/opsteady/opsteady/issues/135)

clusterName: { { .aws_cluster_name } }

vpcId: { { .aws_foundation_vpc_id } }

region: { { .aws_foundation_region } }

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: { { .aws_loadbalancing_iam_role_arn } }

podDisruptionBudget:
  maxUnavailable: 1

watchNamespace: platform

nodeSelector:
  name: system

enableShield: false

enableWaf: false

enableWafv2: false

enableEndpointSlices: true

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - aws-load-balancer-controller
        topologyKey: "kubernetes.io/hostname"
