---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: certificates
  namespace: platform
spec:
  type: 0
  resourceID: {{ .azure_certificates_msi_id }}
  clientID: {{ .azure_certificates_msi_client_id }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: certificates
  namespace: platform
spec:
  azureIdentity: certificates
  selector: certificates
