---
apiVersion: k3d.io/v1alpha3
kind: Simple
name: opsteady
servers: 1
agents: 3

volumes:
  - volume: /tmp/k3d/storage:/var/lib/rancher/k3s/storage
    nodeFilters:
      - agent:*

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:8443
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
    nodeLabels:
      - label: name=system
        nodeFilters:
          - agent:*
