apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: { { .aws_certificates_letsencrypt_email } }
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt
    solvers:
      - dns01:
        route53:
          region: { { .aws_foundation_region } }
          hostedZoneID: { { .aws_foundation_public_zone_id } }
