{{ $public_name := (coalesce .foundation_azure_public_zone_name .foundation_aws_public_zone_name .foundation_local_public_zone_name) }}
---

apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: pinniped-concierge-config
  labels:
    app: pinniped-concierge
spec:
  impersonationProxy:
    mode: enabled
    externalEndpoint: api.{{ $public_name }}{{ if eq .platform_cloud_name "local" }}:8443{{ end }}
    service:
      type: None
      annotations: {}
