image:
  repository: opsteadyos.azurecr.io/amazon/aws-efs-csi-driver

imagePullSecrets:
  - management-acr

sidecars:
  livenessProbe:
    image:
      repository: opsteadyos.azurecr.io/eks-distro/kubernetes-csi/livenessprobe
  nodeDriverRegistrar:
    image:
      repository: opsteadyos.azurecr.io/eks-distro/kubernetes-csi/node-driver-registrar
  csiProvisioner:
    image:
      repository: opsteadyos.azurecr.io/eks-distro/kubernetes-csi/external-provisioner

controller:
  nodeSelector:
    name: system

  # TODO: determine why the affinity setting prevents scheduling:
  # https://github.com/opsteady/opsteady/issues/91
  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #           - aws-efs-csi-driver
  #       topologyKey: "kubernetes.io/hostname"

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: {{ .aws_storage_efs_iam_role_arn }}

node:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: {{ .aws_storage_efs_iam_role_arn }}

storageClasses:
  - name: efs
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      provisioningMode: efs-ap
      fileSystemId: {{ .aws_storage_efs_filesystem_id }}
      directoryPerms: "700"
      gidRangeStart: "1000"
      gidRangeEnd: "2000"
      basePath: "/data"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
