---
replicaCount: 2

image:
  repository: opsteadyos.azurecr.io/dex
  tag: grpc-add-connector
  pullPolicy: Always

imagePullSecrets:
  - name: management-acr

grpc:
  enabled: true

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

priorityClassName: "system-cluster-critical"

nodeSelector:
  name: system

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt{{ if eq .platform_cloud_name "local" }}-staging{{ end }}

  hosts:
    - host: {{ .capabilities_user_auth_oidc_url }}
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - secretName: dex-tls
      hosts:
        - {{ .capabilities_user_auth_oidc_url }}

# See https://dexidp.io/docs/ and https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml
config:
  issuer: https://{{ .capabilities_user_auth_oidc_url }}{{ if eq .platform_cloud_name "local" }}:8443{{ end }}

  storage:
    type: kubernetes
    config:
      inCluster: true

  web:
    http: 127.0.0.1:5556

  telemetry:
    http: 127.0.0.1:5558

  logger:
    level: "debug"
    format: "text"

  expiry:
    deviceRequests: "5m"
    signingKeys: "6h"
    idTokens: "24h"

  oauth2:
    skipApprovalScreen: true

  staticClients:
    - id: pinniped-cli
      redirectURIs:
        - 'http://127.0.0.1:48095/callback'
      name: 'pinniped-cli'
      public: true
    - id: backstage
      redirectURIs:
        - 'http://localhost:7000/api/auth/oidc/handler/frame'
      name: 'Backstage'
      secret: backstage

  connectors:
    - type: microsoft
      id: opsteady
      name: Opsteady
      config:
        clientID: {{ .capabilities_user_auth_oidc_sp_id }}
        clientSecret: {{ .capabilities_user_auth_oidc_sp_secret }}
        redirectURI: https://{{ .capabilities_user_auth_oidc_callback_url }}
        tenant: {{ .capabilities_user_auth_primary_domain }}
        groupNameFormat: id

  enablePasswordDB: false
