name: Docker publish
on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/docker-validate.yml"
      - ".github/workflows/docker-publish.yml"

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      VAULT_ADDRESS: https://vault.management.os.opsteady.com
    permissions:
      id-token: write
      contents: read
    container:
      image: opsteadyos.azurecr.io/cicd:2.7.0 # versioning=semver datasource=docker
      options: --user root
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ secrets.acr_username }}
        password: ${{ secrets.acr_password }}
    steps:
      - name: Get JWT Token
        run: |
          VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV

      - name: Authenticate to Vault
        run: |
          VAULT_TOKEN=$(vault write -address=${{ env.VAULT_ADDRESS }} -field=token auth/gha/login role=workflow jwt=${{ env.VAULT_JWT }})
          echo VAULT_TOKEN=$VAULT_TOKEN >> $GITHUB_ENV
          echo "::add-mask::$VAULT_TOKEN"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure Opsteady CLI
        run: |
          cat <<EOF > config.yaml
          tenant_id: ${{ secrets.tenant_id }}
          management_subscription_id: ${{ secrets.management_subscription_id }}
          management_docker_registry: opsteadyos.azurecr.io
          vault_ca_storage_account_name: opsteadyosvault
          EOF

      - name: Validate base docker
        run: |
          go run main.go validate -c docker-base --cache

      - name: Build base docker
        run: |
          go run main.go build -c docker-base --cache

      - name: Publish base docker
        run: |
          go run main.go publish -c docker-base --cache

      - name: Validate cicd docker
        run: |
          go run main.go validate -c docker-cicd --cache

      - name: Build cicd docker
        run: |
          go run main.go build -c docker-cicd --cache

      - name: Publish cicd docker
        run: |
          go run main.go publish -c docker-cicd --cache
