name: Images Sync

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
        required: false
        default: "Sync images"
  schedule:
    - cron: "0 0 * * *"

jobs:
  images-sync:
    runs-on: ubuntu-latest
    container:
      image: xelalex/dregsy:0.4.2-alpine # versioning=docker datasource=docker
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Sync
        run: |
          skopeo login -u ${{ secrets.acr_username }} -p ${{ secrets.acr_password }} opsteadyos.azurecr.io
          dregsy -config=support/sync/images/dregsy.yaml
        env:
          LOG_LEVEL: trace
