name: Destroy Platform
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Cloud"
        required: true
        default: "azure or aws"
      platform:
        description: "Platform name"
        required: true
        default: "dev-azure or dev-aws"

jobs:
  platform:
    runs-on: ubuntu-20.04
    env:
      VAULT_ADDRESS: https://vault.management.os.opsteady.com
    permissions:
      id-token: write
      contents: read
    container:
      image: opsteadyos.azurecr.io/cicd:2.4.0 # versioning=semver datasource=docker
      options: --user root
      credentials:
        username: ${{ secrets.acr_username }}
        password: ${{ secrets.acr_password }}
    steps:
      - name: Get JWT Token
        run: |
          VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV

      - name: Authenticate to Vault
        run: |
          VAULT_TOKEN=$(vault write -address=${{ env.VAULT_ADDRESS }} -field=token auth/gha/login role=workflow jwt=${{ env.VAULT_JWT }})
          echo VAULT_TOKEN=$VAULT_TOKEN >> $GITHUB_ENV
          echo "::add-mask::$VAULT_TOKEN"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure Opsteady CLI
        run: |
          cat <<EOF > config.yaml
          tenant_id: ${{ secrets.tenant_id }}
          management_subscription_id: ${{ secrets.management_subscription_id }}
          management_docker_registry: opsteadyos.azurecr.io
          management_helm_repository: opsteadyos.azurecr.io
          EOF

      - name: Destroy Certificates capability
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c capabilities-certificates-${{ github.event.inputs.cloud }} --cache

      - name: Destroy DNS capability
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c capabilities-dns-${{ github.event.inputs.cloud }} --cache

      - name: Destroy Kubernetes AAD pod identity
        if: github.event.inputs.cloud == 'azure'
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-pod-identity --cache

      - name: Destroy Kubernetes AWS load balancer controller
        if: github.event.inputs.cloud == 'aws'
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-loadbalancing --cache

      - name: Destroy Kubernetes AWS storage EBS
        if: github.event.inputs.cloud == 'aws'
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-storage-ebs --cache

      - name: Destroy Kubernetes AWS storage EFS
        if: github.event.inputs.cloud == 'aws'
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-storage-efs --cache

      - name: Destroy Kubernetes AWS network policies
        if: github.event.inputs.cloud == 'aws'
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-network-policies --cache

      - name: Destroy Kubernetes bootstrap
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-bootstrap --cache

      - name: Destroy Kubernetes
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c kubernetes-${{ github.event.inputs.cloud }}-cluster --cache

      - name: Destroy foundation
        run: |
          go run main.go destroy --${{ github.event.inputs.cloud }}-id ${{ github.event.inputs.platform }} -c foundation-${{ github.event.inputs.cloud }} --cache
