name: Renovate
on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Check the versions"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Renovate
        uses: renovatebot/github-action@v27.14.0
        with:
          configurationFile: renovate.json
          token: "x-access-token:${{ steps.get_token.outputs.app_token }}"
