name: Renovate
on:
  push:
    branches: add-renovate-workflow
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Renovate
        uses: renovatebot/github-action@v27.14.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
